import type { Locale } from '@/i18n/shared'
import { defaultLocale } from '@/i18n/shared'

/** Matches `localePrefix: 'as-needed'`: default locale paths stay unprefixed. */
export function withLocale(locale: Locale = defaultLocale, path: string) {
  if (locale === defaultLocale) {
    return path
  }

  return path === '/' ? `/${locale}` : `/${locale}${path}`
}

// Base routes without locale
const BASE_ROUTES = {
  ABOUT: '/about',
  ADD_ENTITY: '/entities/add',
  ADD_OPPORTUNITY: '/opportunities/add',
  ADMIN: '/admin',
  ADMIN_ANALYTICS: '/admin/analytics',
  ADMIN_MATCHER: '/admin/matcher',
  ADMIN_NEWS: '/admin/news',
  ADMIN_PERFORMANCE: '/admin/performance',
  ADMIN_SECURITY: '/admin/security',
  ADMIN_SETTINGS: '/admin/settings',
  ADMIN_STORE: '/admin/store',
  ADMIN_STORE_ORDERS: '/admin/store/orders',
  ADMIN_STORE_STOCK: '/admin/store/stock',
  ADMIN_STORE_COMMISSIONS: '/admin/store/commissions',
  ADMIN_USERS: '/admin/users',
  AUTH_STATUS: '/auth/status/[action]/[status]',
  CART: '/store/cart',
  CHECKOUT: '/store/checkout',
  CONFIDENTIAL_ENTITIES: '/confidential/entities',
  CONFIDENTIAL_OPPORTUNITIES: '/confidential/opportunities',
  CONTACT: '/contact',
  CONTACTS: '/contacts',
  CONTACT_STATUS: '/contacts/status/[action]/[status]',
  CONTACT_ADD: '/contacts/add',
  CONTACT_VIEW: (id: string) => `/contacts/${id}`,
  CONTACT_EDIT: (id: string) => `/contacts/${id}/edit`,
  CONTACT_DELETE: (id: string) => `/contacts/${id}/delete`,

  DOCS: '/docs',
  EDITOR: '/editor',
  ENTITIES: '/entities',
  MY_ENTITIES: '/entities/my',
  ENTITY: (id: string) => `/entities/${id}`,
  ENTITY_ADD: '/entities/add',
  ENTITY_EDIT: (id: string) => `/entities/${id}/edit`,
  ENTITY_DELETE: (id: string) => `/entities/${id}/delete`,
  ENTITY_VIEW: (id: string) => `/entities/${id}`,
  ENTITY_STATUS: '/entities/status/[action]/[status]',
  FORGOT_PASSWORD: '/forgot-password',
  HOME: '/',
  INTRO: '/intro',
  KYC: '/kyc',
  LOGIN: '/login',
  MARKETPLACE: '/marketplace',
  MEMBERSHIP: '/membership',
  MESSAGES: '/messages',
  NOTIFICATION_STATUS: '/notifications/status/[action]/[status]',
  OPPORTUNITIES: '/opportunities',
  OPPORTUNITY: (id: string) => `/opportunities/${id}`,
  OPPORTUNITY_STATUS: '/opportunities/status/[action]/[status]',
  PRIVACY: '/privacy',
  PROFILE: '/profile',
  PUBLIC_PROFILE: (username: string) => `/u/${encodeURIComponent(username)}`,
  PUBLICATIONS: '/publications',
  REF_MAGIC: '/refmagic',
  REFMAGIC: '/refmagic',
  REGISTER: '/register',
  SETTINGS: '/settings',
  STORE: '/store',
  STORE_PRODUCT: (id: string) => `/store/${id}`,
  STORE_ORDERS: '/store/orders',
  STORE_ORDER_DETAILS: '/store/orders/[id]',
  TERMS: '/terms',
  UNAUTHORIZED: '/unauthorized',
  VERIFY_EMAIL: '/verify-email',
  WALLET: '/wallet',
  WALLET_CONNECT: '/auth/wallet-connect',
  REFCODES: '/refcodes',
  ADMIN_REFCODES: '/admin/refcodes',
  ADMIN_MODERATION: '/admin/moderation',
  ADMIN_ACTIVITY: '/admin/activity',
  ADMIN_EMAIL_INBOX: '/admin/email-inbox',
  ADMIN_EMAIL_DRAFTS: '/admin/email-drafts',
  ADMIN_EMAIL_CONTACTS: '/admin/email-contacts',
  ADMIN_EMAIL_ANALYTICS: '/admin/email-analytics',
  ADMIN_EMAIL_TASKS: '/admin/email-tasks',
  ADMIN_EMAIL_THREAD: (id: string) => `/admin/email-inbox/${encodeURIComponent(id)}`,
}

// Localized routes
export const ROUTES = {
  ABOUT: (locale: Locale = defaultLocale) => withLocale(locale, '/about'),
  ADD_ENTITY: (locale: Locale = defaultLocale) => withLocale(locale, '/entities/add'),
  ADD_OPPORTUNITY: (locale: Locale = defaultLocale) => withLocale(locale, '/opportunities/add'),
  AUTH_STATUS: (action: string, status: string, locale: Locale = defaultLocale) => withLocale(locale, `/auth/status/${action}/${status}`),
  CART: (locale: Locale = defaultLocale) => withLocale(locale, '/store/cart'),
  CHECKOUT: (locale: Locale = defaultLocale) => withLocale(locale, '/store/checkout'),
  CONFIDENTIAL_ENTITIES: (locale: Locale = defaultLocale) => withLocale(locale, '/confidential/entities'),
  CONFIDENTIAL_OPPORTUNITIES: (locale: Locale = defaultLocale) => withLocale(locale, '/confidential/opportunities'),
  CONTACT: (locale: Locale = defaultLocale) => withLocale(locale, '/contact'),
  CONTACT_STATUS: (action: string, status: string, locale: Locale = defaultLocale) => withLocale(locale, `/contacts/status/${action}/${status}`),
  CONTACT_ADD: (locale: Locale = defaultLocale) => withLocale(locale, '/contacts/add'),
  CONTACT_VIEW: (id: string, locale: Locale = defaultLocale) => withLocale(locale, `/contacts/${id}`),
  CONTACT_EDIT: (id: string, locale: Locale = defaultLocale) => withLocale(locale, `/contacts/${id}/edit`),
  CONTACT_DELETE: (id: string, locale: Locale = defaultLocale) => withLocale(locale, `/contacts/${id}/delete`),
  CONTACTS: (locale: Locale = defaultLocale) => withLocale(locale, '/contacts'),
  DOCS: (locale: Locale = defaultLocale) => withLocale(locale, '/docs'),
  EDITOR: (locale: Locale = defaultLocale) => withLocale(locale, '/editor'),
  ENTITIES: (locale: Locale = defaultLocale) => withLocale(locale, '/entities'),
  MY_ENTITIES: (locale: Locale = defaultLocale) => withLocale(locale, '/entities/my'),
  ENTITY: (id: string, locale: Locale = defaultLocale) => withLocale(locale, `/entities/${id}`),
  ENTITY_EDIT: (id: string, locale: Locale = defaultLocale) =>
    withLocale(locale, `/entities/${id}/edit`),
  ENTITY_DELETE: (id: string, locale: Locale = defaultLocale) =>
    withLocale(locale, `/entities/${id}/delete`),
  ENTITY_STATUS: (action: string, status: string, locale: Locale = defaultLocale) => withLocale(locale, `/entities/status/${action}/${status}`),
  FORGOT_PASSWORD: (locale: Locale = defaultLocale) => withLocale(locale, '/forgot-password'),
  HELP: (locale: Locale = defaultLocale) => withLocale(locale, '/help'),
  HOME: (locale: Locale = defaultLocale) => withLocale(locale, '/'),
  INTRO: (locale: Locale = defaultLocale) => withLocale(locale, '/intro'),
  KYC: (locale: Locale = defaultLocale) => withLocale(locale, '/kyc'),
  LOGIN: (locale: Locale = defaultLocale) => withLocale(locale, '/login'),
  MARKETPLACE: (locale: Locale = defaultLocale) => withLocale(locale, '/marketplace'),
  MEMBERSHIP: (locale: Locale = defaultLocale) => withLocale(locale, '/membership'),
  MESSAGES: (locale: Locale = defaultLocale) => withLocale(locale, '/messages'),
  MY_OPPORTUNITIES: (locale: Locale = defaultLocale) => withLocale(locale, '/opportunities/my'),
  NOTIFICATIONS: (locale: Locale = defaultLocale) => withLocale(locale, '/notifications'),
  NOTIFICATION_STATUS: (action: string, status: string, locale: Locale = defaultLocale) => withLocale(locale, `/notifications/status/${action}/${status}`),
  OPPORTUNITIES: (locale: Locale = defaultLocale) => withLocale(locale, '/opportunities'),
  OPPORTUNITY: (id: string, locale: Locale = defaultLocale) => withLocale(locale, `/opportunities/${id}`),
  OPPORTUNITY_STATUS: (action: string, status: string, locale: Locale = defaultLocale) => withLocale(locale, `/opportunities/status/${action}/${status}`),
  PRIVACY: (locale: Locale = defaultLocale) => withLocale(locale, '/privacy'),
  PROFILE: (locale: Locale = defaultLocale) => withLocale(locale, '/profile'),
  PUBLIC_PROFILE: (username: string, locale: Locale = defaultLocale) =>
    withLocale(locale, `/u/${encodeURIComponent(username)}`),
  PUBLICATIONS: (locale: Locale = defaultLocale) => withLocale(locale, '/publications'),
  REF_MAGIC: (locale: Locale = defaultLocale) => withLocale(locale, '/refmagic'),
  REFMAGIC: (locale: Locale = defaultLocale) => withLocale(locale, '/refmagic'),
  REGISTER: (locale: Locale = defaultLocale) => withLocale(locale, '/register'),
  RESET_PASSWORD: (locale: Locale = defaultLocale) => withLocale(locale, '/reset-password'),
  SETTINGS: (locale: Locale = defaultLocale) => withLocale(locale, '/settings'),
  STORE: (locale: Locale = defaultLocale) => withLocale(locale, '/store'),
  STORE_PRODUCT: (id: string, locale: Locale = defaultLocale) => withLocale(locale, `/store/${id}`),
  STORE_ORDERS: (locale: Locale = defaultLocale) => withLocale(locale, '/store/orders'),
  STORE_ORDER_DETAILS: (locale: Locale = defaultLocale, id: string) => withLocale(locale, `/store/orders/${id}`),
  TERMS: (locale: Locale = defaultLocale) => withLocale(locale, '/terms'),
  UNAUTHORIZED: (locale: Locale = defaultLocale) => withLocale(locale, '/unauthorized'),
  VERIFY_EMAIL: (locale: Locale = defaultLocale) => withLocale(locale, '/verify-email'),
  WALLET: (locale: Locale = defaultLocale) => withLocale(locale, '/wallet'),
  WALLET_CONNECT: (locale: Locale = defaultLocale) => withLocale(locale, '/auth/wallet-connect'),
  REFCODES: (locale: Locale = defaultLocale) => withLocale(locale, '/refcodes'),
  // Admin routes
  ADMIN: (locale: Locale = defaultLocale) => withLocale(locale, '/admin'),
  ADMIN_USERS: (locale: Locale = defaultLocale) => withLocale(locale, '/admin/users'),
  ADMIN_ANALYTICS: (locale: Locale = defaultLocale) => withLocale(locale, '/admin/analytics'),
  ADMIN_SECURITY: (locale: Locale = defaultLocale) => withLocale(locale, '/admin/security'),
  ADMIN_NEWS: (locale: Locale = defaultLocale) => withLocale(locale, '/admin/news'),
  ADMIN_NEWS_CREATE: (locale: Locale = defaultLocale) => withLocale(locale, '/admin/news/create'),
  ADMIN_NEWS_EDIT: (id: string, locale: Locale = defaultLocale) => withLocale(locale, `/admin/news/edit/${id}`),
  ADMIN_NEWS_BULK: (locale: Locale = defaultLocale) => withLocale(locale, '/admin/news/bulk'),
  ADMIN_NEWS_ANALYTICS: (locale: Locale = defaultLocale) => withLocale(locale, '/admin/news/analytics'),
  ADMIN_NEWS_CATEGORIES: (locale: Locale = defaultLocale) => withLocale(locale, '/admin/news/categories'),
  ADMIN_SETTINGS: (locale: Locale = defaultLocale) => withLocale(locale, '/admin/settings'),
  ADMIN_MATCHER: (locale: Locale = defaultLocale) => withLocale(locale, '/admin/matcher'),
  ADMIN_VERIFICATION: (locale: Locale = defaultLocale) => withLocale(locale, '/admin/verification'),
  ADMIN_PERFORMANCE: (locale: Locale = defaultLocale) => withLocale(locale, '/admin/performance'),
  ADMIN_STORE: (locale: Locale = defaultLocale) => withLocale(locale, '/admin/store'),
  ADMIN_STORE_ORDERS: (locale: Locale = defaultLocale) => withLocale(locale, '/admin/store/orders'),
  ADMIN_STORE_STOCK: (locale: Locale = defaultLocale) => withLocale(locale, '/admin/store/stock'),
  ADMIN_STORE_COMMISSIONS: (locale: Locale = defaultLocale) => withLocale(locale, '/admin/store/commissions'),
  ADMIN_REFCODES: (locale: Locale = defaultLocale) => withLocale(locale, '/admin/refcodes'),
  ADMIN_MODERATION: (locale: Locale = defaultLocale) => withLocale(locale, '/admin/moderation'),
  ADMIN_ACTIVITY: (locale: Locale = defaultLocale) => withLocale(locale, '/admin/activity'),
  ADMIN_EMAIL_INBOX: (locale: Locale = defaultLocale) => withLocale(locale, '/admin/email-inbox'),
  ADMIN_EMAIL_DRAFTS: (locale: Locale = defaultLocale) => withLocale(locale, '/admin/email-drafts'),
  ADMIN_EMAIL_CONTACTS: (locale: Locale = defaultLocale) => withLocale(locale, '/admin/email-contacts'),
  ADMIN_EMAIL_ANALYTICS: (locale: Locale = defaultLocale) => withLocale(locale, '/admin/email-analytics'),
  ADMIN_EMAIL_TASKS: (locale: Locale = defaultLocale) => withLocale(locale, '/admin/email-tasks'),
  ADMIN_EMAIL_THREAD: (id: string, locale: Locale = defaultLocale) =>
    withLocale(locale, `/admin/email-inbox/${encodeURIComponent(id)}`),
  ADMIN_NEWS_COMMENTS: (locale: Locale = defaultLocale) => withLocale(locale, '/admin/news/comments'),
  ADMIN_NEWS_TAGS: (locale: Locale = defaultLocale) => withLocale(locale, '/admin/news/tags'),
  // Vendor Routes - Multi-Vendor Marketplace
  VENDOR_START: (locale: Locale = defaultLocale) => withLocale(locale, '/vendor/start'),
  VENDOR_DASHBOARD: (locale: Locale = defaultLocale) => withLocale(locale, '/vendor/dashboard'),
  VENDOR_PRODUCTS: (locale: Locale = defaultLocale) => withLocale(locale, '/vendor/products'),
  VENDOR_PRODUCTS_ADD: (locale: Locale = defaultLocale) => withLocale(locale, '/vendor/products/add'),
  VENDOR_PRODUCTS_EDIT: (locale: Locale = defaultLocale, id: string) => withLocale(locale, `/vendor/products/${id}/edit`),
  VENDOR_ORDERS: (locale: Locale = defaultLocale) => withLocale(locale, '/vendor/orders'),
  VENDOR_EARNINGS: (locale: Locale = defaultLocale) => withLocale(locale, '/vendor/earnings'),
  VENDOR_SETTINGS: (locale: Locale = defaultLocale) => withLocale(locale, '/vendor/settings'),
  VENDOR_STOCK: (locale: Locale = defaultLocale) => withLocale(locale, '/vendor/stock'),
  VENDOR_STOREFRONT: (locale: Locale = defaultLocale, vendorId: string) => withLocale(locale, `/store/vendors/${vendorId}`)
}

// Legacy routes for backward compatibility (these will redirect to localized versions)
export const LEGACY_ROUTES = BASE_ROUTES

export const API_ROUTES = {
  LOGIN: '/api/auth/login',
  LOGOUT: '/api/auth/logout',
  REGISTER: '/api/auth/register',
  GET_ENTITIES: '/api/entities',
  GET_ENTITY: (id: string) => `/api/entities/${id}`,
  CREATE_ENTITY: '/api/entities/create',
  UPDATE_ENTITY: (id: string) => `/api/entities/${id}`,
  DELETE_ENTITY: (id: string) => `/api/entities/${id}`,
  VERIFY_ENTITY: (id: string) => `/api/entities/${id}/verify`,
  INVITE_ENTITY_MEMBER: (id: string) => `/api/entities/${id}/invite`,
  ENTITY_ANALYTICS: (id: string) => `/api/entities/${id}/analytics`,
  UPLOAD_ENTITY: '/api/entities/upload',
  UPLOADS: '/api/uploads',
  VERIFICATION_PROCEDURE_ME: '/api/verification/procedures/me',
  VERIFICATION_PROCEDURE_DOCUMENTS: (procedureNumber: string) =>
    `/api/verification/procedures/${procedureNumber}/documents`,
  VERIFICATION_DOCUMENT: (procedureNumber: string, documentId: string) =>
    `/api/verification/documents/${procedureNumber}/${documentId}`,
  ADMIN_VERIFICATION_QUEUE: '/api/admin/verification/queue',
  ADMIN_VERIFICATION_ACTION: (procedureNumber: string, action: string) =>
    `/api/admin/verification/procedures/${procedureNumber}/${action}`,
  GET_OPPORTUNITIES: '/api/opportunities',
  SUBMIT_CONTACT_FORM: '/api/contact',
} as const

export { getSocialLinks } from '@/lib/ring-config-core'