import 'server-only'

import { randomUUID } from 'crypto'
import {
  TaskRepository,
  TaskCreateInput,
  TaskUpdateInput,
  TaskCompleteInput,
  TaskSearchParams,
  EmailTask,
} from '@/services/email/crm/task-service'
import { parseIsoDate, queryDocs, readDoc, upsertDoc, deleteDoc } from '@/features/email-crm/lib/jsonb-collection'

const COLLECTION = 'email_tasks'

function hydrateTask(id: string, raw: Record<string, unknown>): EmailTask {
  return {
    id,
    threadId: String(raw.threadId ?? ''),
    messageId: raw.messageId != null ? String(raw.messageId) : null,
    title: String(raw.title ?? ''),
    description: raw.description != null ? String(raw.description) : null,
    taskType: (raw.taskType as EmailTask['taskType']) ?? 'follow_up',
    dueDate: parseIsoDate(raw.dueDate),
    assignedTo: raw.assignedTo != null ? String(raw.assignedTo) : null,
    status: (raw.status as EmailTask['status']) ?? 'open',
    priority: (raw.priority as EmailTask['priority']) ?? 'normal',
    autoGenerated: Boolean(raw.autoGenerated),
    triggerReason: raw.triggerReason != null ? String(raw.triggerReason) : null,
    completedAt: parseIsoDate(raw.completedAt),
    completedBy: raw.completedBy != null ? String(raw.completedBy) : null,
    completionNotes: raw.completionNotes != null ? String(raw.completionNotes) : null,
    createdAt: parseIsoDate(raw.createdAt) ?? new Date(),
    updatedAt: parseIsoDate(raw.updatedAt) ?? new Date(),
  }
}

function toStored(task: Partial<EmailTask>): Record<string, unknown> {
  return {
    threadId: task.threadId,
    messageId: task.messageId,
    title: task.title,
    description: task.description,
    taskType: task.taskType,
    dueDate: task.dueDate?.toISOString() ?? null,
    assignedTo: task.assignedTo,
    status: task.status,
    priority: task.priority,
    autoGenerated: task.autoGenerated,
    triggerReason: task.triggerReason,
    completedAt: task.completedAt?.toISOString() ?? null,
    completedBy: task.completedBy,
    completionNotes: task.completionNotes,
    createdAt: task.createdAt?.toISOString(),
    updatedAt: task.updatedAt?.toISOString(),
  }
}

export class JsonbTaskRepository implements TaskRepository {
  async findById(id: string): Promise<EmailTask | null> {
    const doc = await readDoc<Record<string, unknown>>(COLLECTION, id)
    return doc ? hydrateTask(doc.id, doc) : null
  }

  async findByThreadId(threadId: string): Promise<EmailTask[]> {
    const rows = await queryDocs<Record<string, unknown>>({
      collection: COLLECTION,
      filters: [{ field: 'threadId', operator: '=', value: threadId }],
      limit: 200,
    })
    return rows.map((row) => hydrateTask(row.id, row))
  }

  async create(input: TaskCreateInput): Promise<EmailTask> {
    const id = `task_${randomUUID()}`
    const now = new Date()
    const task: EmailTask = {
      id,
      threadId: input.threadId,
      messageId: input.messageId ?? null,
      title: input.title,
      description: input.description ?? null,
      taskType: input.taskType,
      dueDate: input.dueDate ?? (input.dueDays != null ? new Date(Date.now() + input.dueDays * 86400000) : null),
      assignedTo: input.assignedTo ?? null,
      status: 'open',
      priority: input.priority ?? 'normal',
      autoGenerated: input.autoGenerated ?? false,
      triggerReason: input.triggerReason ?? null,
      completedAt: null,
      completedBy: null,
      completionNotes: null,
      createdAt: now,
      updatedAt: now,
    }
    await upsertDoc(COLLECTION, id, toStored(task))
    return task
  }

  async update(id: string, input: TaskUpdateInput): Promise<EmailTask> {
    const existing = await this.findById(id)
    if (!existing) throw new Error('Task not found')
    const updated: EmailTask = { ...existing, ...input, updatedAt: new Date() }
    await upsertDoc(COLLECTION, id, toStored(updated))
    return updated
  }

  async complete(id: string, input: TaskCompleteInput): Promise<EmailTask> {
    const existing = await this.findById(id)
    if (!existing) throw new Error('Task not found')
    const now = new Date()
    const completed: EmailTask = {
      ...existing,
      status: 'completed',
      completedAt: now,
      completedBy: input.completedBy,
      completionNotes: input.completionNotes ?? null,
      updatedAt: now,
    }
    await upsertDoc(COLLECTION, id, toStored(completed))
    return completed
  }

  async search(params: TaskSearchParams): Promise<EmailTask[]> {
    const filters = []
    if (params.threadId) {
      filters.push({ field: 'threadId', operator: '=', value: params.threadId })
    }
    if (params.assignedTo) {
      filters.push({ field: 'assignedTo', operator: '=', value: params.assignedTo })
    }
    if (params.taskType) {
      filters.push({ field: 'taskType', operator: '=', value: params.taskType })
    }

    let results = (await queryDocs<Record<string, unknown>>({
      collection: COLLECTION,
      filters,
      orderBy: [{ field: 'createdAt', direction: 'desc' }],
      limit: 500,
    })).map((row) => hydrateTask(row.id, row))

    if (params.status) {
      const statuses = Array.isArray(params.status) ? params.status : [params.status]
      results = results.filter((t) => statuses.includes(t.status))
    }
    if (params.priority) {
      const priorities = Array.isArray(params.priority) ? params.priority : [params.priority]
      results = results.filter((t) => priorities.includes(t.priority))
    }
    if (params.dueBefore) {
      results = results.filter((t) => t.dueDate && t.dueDate <= params.dueBefore!)
    }
    if (params.dueAfter) {
      results = results.filter((t) => t.dueDate && t.dueDate >= params.dueAfter!)
    }

    const offset = params.offset ?? 0
    return results.slice(offset, offset + (params.limit ?? 100))
  }

  async markOverdue(): Promise<number> {
    const open = await this.search({ status: ['open', 'in_progress'], limit: 500 })
    const now = new Date()
    let count = 0
    for (const task of open) {
      if (task.dueDate && task.dueDate < now) {
        await this.update(task.id, { status: 'overdue' })
        count++
      }
    }
    return count
  }

  async delete(id: string): Promise<void> {
    await deleteDoc(COLLECTION, id)
  }
}
