/**
 * Ring API tree — founder-friendly catalog of App Router `/api/*` routes.
 * Source of truth: Next.js build route list (ring-platform.org, 2026-07-10).
 * Methods are the common verbs for each path; see route handlers for exact exports.
 */

export type ApiHttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE'

export type ApiEndpointNode = {
  id: string
  path: string
  /** Short founder-facing title */
  title: string
  /** Plain-language what this endpoint does */
  summary: string
  methods: ApiHttpMethod[]
  /** Optional deep-doc path under /docs/... */
  docsHref?: string
}

export type ApiFamilyNode = {
  id: string
  label: string
  /** One-line founder pitch for the family */
  blurb: string
  /** Family procedure / domain doc — used when a leaf has no docsHref */
  docsHref?: string
  /** Short label for the docs link (founder-friendly) */
  docsLabel?: string
  endpoints: ApiEndpointNode[]
}

function ep(
  path: string,
  title: string,
  summary: string,
  methods: ApiHttpMethod[],
  docsHref?: string,
): ApiEndpointNode {
  return {
    id: path,
    path: `/api/${path}`,
    title,
    summary,
    methods,
    docsHref,
  }
}

/** 244 App Router API routes grouped for visual browsing */
export const API_TREE_FAMILIES: ApiFamilyNode[] = [
  {
    id: 'auth',
    label: 'Auth & identity',
    blurb: 'Sign-in, sessions, usernames, and wallet login helpers.',
    docsHref: '/docs/api/authentication',
    docsLabel: 'Authentication API',
    endpoints: [
      ep('auth/[...nextauth]', 'Auth.js', 'Sign-in, sign-out, and session callbacks (Auth.js v5).', ['GET', 'POST'], '/docs/api/authentication'),
      ep('auth/check-username', 'Check username', 'Ask whether a username is available before signup.', ['GET', 'POST']),
      ep('auth/crypto/generateNonce', 'Wallet nonce', 'Issue a one-time challenge for crypto wallet login.', ['GET', 'POST']),
      ep('auth/refresh-session', 'Refresh session', 'Refresh the signed-in session without a full re-login.', ['POST']),
      ep('auth/telegram/callback', 'Telegram login', 'Complete Telegram Login Widget authentication.', ['GET', 'POST']),
      ep('account/restore-request', 'Restore account', 'Request help restoring a locked or deleted account.', ['POST']),
      ep('set-user-role', 'Set user role', 'Assign a platform role (guarded; prefer admin routes in production).', ['POST']),
    ],
  },
  {
    id: 'profile',
    label: 'Profile & people',
    blurb: 'Member profiles, preferences, favorites, and people search.',
    docsHref: '/docs/api/authentication',
    docsLabel: 'Auth & identity docs',
    endpoints: [
      ep('profile', 'My profile', 'Read or update the signed-in member profile.', ['GET', 'PUT', 'PATCH'], '/docs/api/authentication'),
      ep('profile/upload', 'Profile media', 'Upload avatar or profile media.', ['POST']),
      ep('users/search', 'Search people', 'Find members by name or username.', ['GET']),
      ep('users/favorites', 'Favorites', 'List or change saved favorites.', ['GET', 'POST', 'DELETE']),
      ep('users/preferences', 'Preferences', 'Read or save personal preference settings.', ['GET', 'PUT', 'PATCH']),
      ep('settings', 'App settings', 'Read or update account-level settings.', ['GET', 'PUT', 'PATCH']),
      ep('ring/contacts', 'Ring contacts', 'List or manage Ring address-book contacts.', ['GET', 'POST']),
      ep('ring/contacts/[contactId]', 'Contact detail', 'Update or remove one contact.', ['GET', 'PATCH', 'DELETE']),
      ep('ring/contacts/resolve-wallet', 'Resolve wallet', 'Map a contact to a wallet address when known.', ['POST']),
    ],
  },
  {
    id: 'messaging',
    label: 'Messaging & calls',
    blurb: 'Conversations, messages, typing, uploads, and call invites.',
    docsHref: '/docs/api/messaging',
    docsLabel: 'Messaging API',
    endpoints: [
      ep('conversations', 'Conversations', 'List or start conversations.', ['GET', 'POST'], '/docs/api/messaging'),
      ep('conversations/[id]', 'Conversation', 'Open or update one conversation thread.', ['GET', 'PATCH', 'DELETE']),
      ep('conversations/[id]/messages', 'Messages', 'Load or send messages in a conversation.', ['GET', 'POST']),
      ep('conversations/[id]/read', 'Mark read', 'Mark messages as read.', ['POST']),
      ep('conversations/[id]/typing', 'Typing', 'Broadcast typing indicators.', ['POST']),
      ep('conversations/[id]/call-invite', 'Call invite', 'Invite peers into a voice/video call.', ['POST'], '/docs/features/webrtc-calls'),
      ep('conversations/upload', 'Chat upload', 'Upload attachments for chat.', ['POST']),
      ep('messages/[id]', 'Message', 'Edit or delete a single message.', ['GET', 'PATCH', 'DELETE']),
      ep('messages/[id]/reactions', 'Reactions', 'Add or remove emoji reactions.', ['GET', 'POST', 'DELETE']),
      ep('webrtc/ice-servers', 'ICE servers', 'Fetch TURN/STUN config for WebRTC calls.', ['GET'], '/docs/features/webrtc-calls'),
      ep('comments', 'Comments', 'List or post comments on content.', ['GET', 'POST']),
      ep('comments/[id]/like', 'Like comment', 'Like or unlike a comment.', ['POST']),
    ],
  },
  {
    id: 'notifications',
    label: 'Notifications & push',
    blurb: 'In-app inbox plus FCM device registration for mobile push.',
    docsHref: '/docs/api/notifications',
    docsLabel: 'Notifications API',
    endpoints: [
      ep('notifications', 'Inbox', 'List notifications for the signed-in user.', ['GET'], '/docs/api/notifications'),
      ep('notifications/[id]/read', 'Mark one read', 'Mark a single notification as read.', ['POST']),
      ep('notifications/read-all', 'Mark all read', 'Clear the unread badge in one step.', ['POST']),
      ep('notifications/preferences', 'Notify prefs', 'Control which alerts you receive.', ['GET', 'PUT', 'PATCH']),
      ep('notifications/fcm/register', 'Register device', 'Register an FCM token for push.', ['POST'], '/docs/features/push-notifications-fcm'),
      ep('notifications/fcm/test', 'Test push', 'Send a test push (dev/admin).', ['POST']),
      ep('notifications/fcm/tokens/count', 'Token count', 'Count registered push tokens.', ['GET']),
    ],
  },
  {
    id: 'entities',
    label: 'Entities & opportunities',
    blurb: 'Organizations, projects, and opportunity matching — the Ring core.',
    docsHref: '/docs/api/entities',
    docsLabel: 'Entities API',
    endpoints: [
      ep('entities', 'Entities list', 'Browse entities (orgs, projects, places).', ['GET'], '/docs/api/entities'),
      ep('entities/create', 'Create entity', 'Create a new entity.', ['POST']),
      ep('entities/[id]', 'Entity detail', 'Read or update one entity.', ['GET', 'PUT', 'PATCH', 'DELETE']),
      ep('entities/[id]/analytics', 'Entity analytics', 'Usage and engagement stats for an entity.', ['GET']),
      ep('entities/[id]/invite', 'Invite members', 'Invite people into an entity.', ['POST']),
      ep('entities/[id]/verify', 'Verify entity', 'Start or continue entity verification.', ['POST']),
      ep('entities/upload', 'Entity media', 'Upload entity images or files.', ['POST']),
      ep('opportunities', 'Opportunities', 'List or create opportunities.', ['GET', 'POST'], '/docs/api/opportunities'),
      ep('opportunities/[id]', 'Opportunity detail', 'Read, update, or delete one opportunity.', ['GET', 'PUT', 'PATCH', 'DELETE']),
      ep('opportunities/search', 'Search opportunities', 'Full-text / filter search.', ['GET', 'POST']),
      ep('opportunities/upload', 'Opportunity media', 'Upload opportunity media.', ['POST']),
      ep('opportunities/my', 'My opportunities', 'Cursor-paginated owner listings.', ['GET']),
      ep('confidential/entities', 'Confidential entities', 'Access restricted entity payloads.', ['GET']),
      ep('confidential/opportunities', 'Confidential opps', 'Access restricted opportunity payloads.', ['GET']),
    ],
  },
  {
    id: 'news',
    label: 'News & publications',
    blurb: 'Newsroom posts, categories, RSS, promotions, and scholarly publications.',
    docsHref: '/docs/features/news',
    docsLabel: 'News feature',
    endpoints: [
      ep('news', 'News feed', 'List news articles.', ['GET'], '/docs/features/news'),
      ep('news/[id]', 'News article', 'Read, update, or delete one article.', ['GET', 'PUT', 'PATCH', 'DELETE']),
      ep('news/[id]/like', 'Like news', 'Like or unlike an article.', ['POST']),
      ep('news/bulk', 'Bulk news', 'Batch create or update news items.', ['POST']),
      ep('news/categories', 'Categories', 'List or create news categories.', ['GET', 'POST']),
      ep('news/categories/[id]', 'Category', 'Update or delete a category.', ['GET', 'PUT', 'PATCH', 'DELETE']),
      ep('news/generate', 'AI generate news', 'Generate a draft article with AI.', ['POST']),
      ep('news/rss', 'RSS feed', 'Public RSS output for syndication.', ['GET']),
      ep('news/promotion/submit', 'Promote news', 'Submit a paid news promotion.', ['POST']),
      ep('news/promotion/wayforpay-webhook', 'Promo webhook', 'WayForPay callback for news promotions.', ['POST']),
      ep('publications', 'Publications', 'List scholarly / long-form publications.', ['GET']),
      ep('publications/[id]', 'Publication', 'Read or update a publication.', ['GET', 'PUT', 'PATCH']),
      ep('publications/[id]/versions', 'Versions', 'List publication version history.', ['GET']),
      ep('collab/[publicationId]/snapshot', 'Collab snapshot', 'Load a live collaboration snapshot.', ['GET']),
      ep('citations/lookup', 'Citation lookup', 'Resolve bibliographic citations.', ['GET', 'POST']),
      ep('images/generate', 'Generate image', 'AI image generation for content.', ['POST']),
    ],
  },
  {
    id: 'store',
    label: 'Store & shipping',
    blurb: 'Catalog, checkout, orders, reviews, and Nova Poshta helpers.',
    docsHref: '/docs/api/store',
    docsLabel: 'Store API',
    endpoints: [
      ep('store/products', 'Products', 'Browse the product catalog.', ['GET'], '/docs/api/store'),
      ep('store/products/[id]/reviews', 'Product reviews', 'List or post product reviews.', ['GET', 'POST']),
      ep('store/products/[id]/agent-chat', 'Product agent', 'Chat with a product-scoped AI agent.', ['POST']),
      ep('store/price-range', 'Price range', 'Min/max prices for filters.', ['GET']),
      ep('store/checkout', 'Checkout', 'Create a checkout / order draft.', ['POST']),
      ep('store/orders', 'My orders', 'List orders for the signed-in buyer.', ['GET']),
      ep('store/orders/[id]', 'Order detail', 'Read one order.', ['GET']),
      ep('store/payments/wayforpay', 'Pay with WayForPay', 'Start card payment for a store order.', ['POST']),
      ep('store/payments/card', 'Pay with card', 'Card checkout alias (PaymentConductor card rail).', ['POST']),
      ep('store/payments/stripe', 'Pay with Stripe', 'Stripe checkout for a store order.', ['POST']),
      ep('store/payments/paypal', 'Pay with PayPal', 'PayPal Orders v2 via PaymentConductor.', ['POST']),
      ep('store/payments/wayforpay/webhook', 'Store WFP webhook', 'WayForPay server callback for store orders.', ['POST']),
      ep('store/payments/credit', 'Pay with credit', 'Pay a store order from platform credit.', ['POST']),
      ep('store/payments/token', 'Pay with native token', 'Pay store order with native token rail.', ['POST']),
      ep('store/payments/[orderId]/status', 'Payment status', 'Poll payment status for an order.', ['GET']),
      ep('shipping/novapost/cities', 'Nova Poshta cities', 'Lookup cities for shipping.', ['GET']),
      ep('shipping/novapost/warehouses', 'Nova Poshta warehouses', 'Lookup warehouses / branches.', ['GET']),
      ep('vendor/status', 'Vendor status', 'Current vendor onboarding status.', ['GET']),
      ep('vendor/check-status', 'Check vendor', 'Re-check vendor eligibility.', ['GET', 'POST']),
      ep('erp/stock/initialize', 'Init stock', 'Initialize ERP stock for a vendor catalog.', ['POST']),
      ep('admin/orders/[id]/status', 'Admin order status', 'Ops: change fulfillment status.', ['PATCH', 'POST']),
    ],
  },
  {
    id: 'membership',
    label: 'Membership & payments',
    blurb: 'Subscriptions and payment rails — card, credit, PayPal, token.',
    docsHref: '/docs/features/payment-conductor',
    docsLabel: 'PaymentConductor',
    endpoints: [
      ep('membership/subscription/create', 'Start subscription', 'Create a membership subscription.', ['POST'], '/docs/features/subscriptions'),
      ep('membership/subscription/status', 'Subscription status', 'Read current membership status.', ['GET']),
      ep('membership/subscription/cancel', 'Cancel subscription', 'Cancel renewals.', ['POST']),
      ep('membership/payment/card', 'Pay by card', 'Membership upgrade via WayForPay card.', ['POST']),
      ep('membership/payment/credit', 'Pay by credit', 'Membership upgrade from credit balance.', ['POST']),
      ep('membership/payment/paypal', 'Pay by PayPal', 'Membership upgrade via PayPal (when enabled).', ['POST']),
      ep('membership/payment/token', 'Pay by token', 'Membership upgrade with RING / on-chain token.', ['POST']),
      ep('payments/wayforpay/webhook', 'WayForPay webhook', 'Global WayForPay payment callback.', ['POST'], '/docs/features/wayforpay-integration'),
      ep('payments/stripe/webhook', 'Stripe webhook', 'Stripe payment callback (when configured).', ['POST']),
      ep('payments/paypal/webhook', 'PayPal webhook', 'PayPal Orders/Subscriptions callback (verified).', ['POST']),
      ep('prices/conversion', 'Price conversion', 'Desk oracle: native_token ↔ main_currency (POST convert, GET rates). Prefer @/lib/ring-oracle server-side.', ['GET', 'POST']),
      ep('balance', 'Legacy balance', 'Legacy balance read (prefer wallet/credit routes).', ['GET']),
    ],
  },
  {
    id: 'wallet',
    label: 'Wallet & credits',
    blurb: 'Platform credit, transfers, desk quotes, and token balances.',
    docsHref: '/docs/api/wallet',
    docsLabel: 'Wallet API',
    endpoints: [
      ep('wallet/ensure', 'Ensure wallet', 'Create a wallet record if missing.', ['POST'], '/docs/api/wallet'),
      ep('wallet/list', 'List wallets', 'List wallets linked to the user.', ['GET']),
      ep('wallet/set-primary', 'Set primary', 'Choose the primary wallet.', ['POST']),
      ep('wallet/balance', 'Wallet balance', 'Read on-platform wallet balance summary.', ['GET']),
      ep('wallet/activity', 'Wallet activity', 'Recent wallet activity feed (replaces deprecated /api/wallet/history).', ['GET']),
      ep('wallet/transfer', 'Transfer', 'External EVM custodial POL path when chains.enabled includes evm.', ['POST']),
      ep('wallet/credit/balance', 'Credit balance', 'Read spendable platform credit.', ['GET', 'PUT']),
      ep('wallet/credit/history', 'Credit history', 'Credit ledger history.', ['GET']),
      ep('wallet/credit/spend', 'Spend credit', 'POST: debit fiat credit-balance points (WalletConductor; rate = credit.creditBalanceUnitToMainCurrency).', ['POST']),
      ep('wallet/credit/topup', 'Top up credit', 'POST: chain-proof credit add (card top-up uses PaymentConductor wallet_topup).', ['POST']),
      ep('wallet/desk/quote', 'Desk quote', 'Get a quote from the wallet desk.', ['GET']),
      ep('wallet/desk/execute', 'Desk execute', 'Execute a quoted desk trade.', ['POST']),
      ep('wallet/token/balance', 'Token balance', 'Read RING / chain token balance.', ['GET']),
      ep('wallet/token/transfer', 'Token transfer', 'Transfer RING / chain tokens.', ['POST']),
    ],
  },
  {
    id: 'admin',
    label: 'Admin & ops',
    blurb: 'Operator console APIs — users, email CRM, fraud, processes, Web3 settings.',
    docsHref: '/docs/api/admin',
    docsLabel: 'Admin API',
    endpoints: [
      ep('admin/status', 'Admin status', 'Health of admin capabilities for the current operator.', ['GET'], '/docs/api/admin'),
      ep('admin/activity', 'Admin activity', 'Recent operator / platform activity.', ['GET']),
      ep('admin/save', 'Admin save', 'Persist admin configuration payloads.', ['POST']),
      ep('admin/platform-settings', 'Platform settings', 'Read or write platform-wide settings.', ['GET', 'PUT', 'PATCH']),
      ep('admin/whitelabel/save', 'Whitelabel save', 'Save white-label branding config.', ['POST']),
      ep('admin/set-user-role', 'Set role', 'Change a user role from admin.', ['POST']),
      ep('admin/migrate-users', 'Migrate users', 'Run user migration utilities.', ['POST']),
      ep('admin/users/[id]', 'Admin user', 'Load admin user detail.', ['GET']),
      ep('admin/users/[id]/role', 'User role', 'Patch user role.', ['PATCH', 'POST']),
      ep('admin/users/[id]/status', 'User status', 'Suspend / restore a user.', ['PATCH', 'POST']),
      ep('admin/users/[id]/verification', 'User verification', 'Admin verification actions.', ['PATCH', 'POST']),
      ep('admin/users/[id]/payments', 'User payments', 'Payment history for a user (ledger).', ['GET']),
      ep('admin/subscriptions', 'Subscriptions', 'List memberships for ops.', ['GET']),
      ep('admin/subscriptions/stats', 'Subscription stats', 'Aggregate subscription metrics.', ['GET']),
      ep('admin/entity-moderation', 'Entity moderation', 'Queue of entities needing review.', ['GET']),
      ep('admin/entity-moderation/block', 'Block entity', 'Block or unblock an entity.', ['POST']),
      ep('admin/fraud/candidates', 'Fraud candidates', 'Users flagged for fraud review.', ['GET']),
      ep('admin/fraud/users/[id]/telemetry', 'Fraud telemetry', 'Telemetry for a fraud candidate.', ['GET']),
      ep('admin/matcher/analytics', 'Matcher analytics', 'AI matcher performance metrics.', ['GET']),
      ep('admin/verification/queue', 'Verification queue', 'Pending KYC / verification cases.', ['GET']),
      ep('admin/verification/procedures/[procedureNumber]/[action]', 'Verification action', 'Approve / reject / request more docs.', ['POST']),
      ep('admin/email/threads', 'Email threads', 'CRM email threads.', ['GET'], '/docs/api/email-ai-crm'),
      ep('admin/email/threads/[id]', 'Email thread', 'One CRM thread.', ['GET']),
      ep('admin/email/contacts', 'Email contacts', 'CRM contacts.', ['GET']),
      ep('admin/email/drafts', 'Email drafts', 'AI / operator email drafts.', ['GET'], '/docs/api/email-ai-crm'),
      ep('admin/email/drafts/[id]/approve', 'Approve draft', 'Approve a draft for send.', ['POST']),
      ep('admin/email/drafts/[id]/reject', 'Reject draft', 'Reject a draft.', ['POST']),
      ep('admin/email/drafts/[id]/send', 'Send draft', 'Send an approved draft.', ['POST']),
      ep('admin/email/tasks', 'Email tasks', 'Follow-up tasks from email CRM.', ['GET']),
      ep('admin/email/tasks/[id]/complete', 'Complete task', 'Mark an email task done.', ['POST']),
      ep('admin/email/analytics', 'Email analytics', 'CRM email performance.', ['GET'], '/docs/api/email-ai-crm'),
      ep('admin/processes', 'Background processes', 'List runnable admin processes.', ['GET']),
      ep('admin/processes/[id]/run', 'Run process', 'Trigger a process run.', ['POST']),
      ep('admin/processes/[id]/history', 'Process history', 'Past runs for a process.', ['GET']),
      ep('admin/public-pools', 'Admin pools', 'Manage public contribution pools.', ['GET', 'POST']),
      ep('admin/public-pools/[id]', 'Admin pool', 'Update one pool.', ['GET', 'PATCH']),
      ep('admin/public-pools/[id]/status', 'Pool status', 'Change pool status.', ['POST']),
      ep('admin/web3/settings', 'Web3 settings', 'Chain / contract settings.', ['GET', 'PUT', 'PATCH']),
      ep('admin/web3/token', 'Web3 token', 'Token configuration for ops.', ['GET', 'PUT', 'PATCH']),
      ep('admin/web3/gas-reserve', 'Gas reserve', 'Monitor / top gas reserve.', ['GET', 'POST']),
      ep('telegram/admin-bot/webhook', 'Telegram admin bot', 'Webhook for the Telegram admin bot.', ['POST'], '/docs/features/manage-via-telegram'),
    ],
  },
  {
    id: 'mcp',
    label: 'MCP agent API',
    blurb: 'Machine-facing `/api/mcp/v1/*` — same domains, agent-friendly contracts.',
    docsHref: '/docs/development/ring-mcp',
    docsLabel: 'Ring MCP',
    endpoints: [
      ep('mcp/v1/meta/health', 'MCP health', 'Agent health check.', ['GET'], '/docs/development/ring-mcp'),
      ep('mcp/v1/meta/context', 'MCP context', 'Platform context for agents.', ['GET']),
      ep('mcp/v1/users', 'MCP users', 'List users (agent scope).', ['GET']),
      ep('mcp/v1/users/[id]', 'MCP user', 'User detail for agents.', ['GET']),
      ep('mcp/v1/users/[id]/role', 'MCP set role', 'Change role via MCP.', ['POST', 'PATCH']),
      ep('mcp/v1/entities', 'MCP entities', 'List entities.', ['GET']),
      ep('mcp/v1/entities/[id]', 'MCP entity', 'Entity detail.', ['GET']),
      ep('mcp/v1/entities/search', 'MCP entity search', 'Search entities.', ['GET', 'POST']),
      ep('mcp/v1/opportunities', 'MCP opportunities', 'List or create opportunities.', ['GET', 'POST']),
      ep('mcp/v1/opportunities/[id]', 'MCP opportunity', 'Opportunity detail.', ['GET']),
      ep('mcp/v1/opportunities/search', 'MCP opp search', 'Search opportunities.', ['GET', 'POST']),
      ep('mcp/v1/opportunities/[id]/match', 'MCP match', 'Run matcher for an opportunity.', ['POST']),
      ep('mcp/v1/news', 'MCP news', 'List news.', ['GET']),
      ep('mcp/v1/news/[id]', 'MCP news item', 'News detail.', ['GET']),
      ep('mcp/v1/news/categories', 'MCP categories', 'News categories.', ['GET']),
      ep('mcp/v1/news/generate', 'MCP generate news', 'Generate news draft.', ['POST']),
      ep('mcp/v1/news/[id]/score', 'MCP score news', 'Score a draft.', ['POST']),
      ep('mcp/v1/news/[id]/approve', 'MCP approve', 'Approve news.', ['POST']),
      ep('mcp/v1/news/[id]/reject', 'MCP reject', 'Reject news.', ['POST']),
      ep('mcp/v1/news/[id]/publish', 'MCP publish', 'Publish news.', ['POST']),
      ep('mcp/v1/messaging/conversations', 'MCP conversations', 'Agent messaging conversations.', ['GET', 'POST']),
      ep('mcp/v1/messaging/messages', 'MCP messages', 'Send / list messages via MCP.', ['GET', 'POST']),
      ep('mcp/v1/messaging/fcm', 'MCP FCM', 'Push registration via MCP.', ['POST']),
      ep('mcp/v1/notifications', 'MCP notifications', 'List notifications.', ['GET']),
      ep('mcp/v1/notifications/send', 'MCP send notify', 'Send a notification.', ['POST']),
      ep('mcp/v1/credit/balance', 'MCP credit balance', 'Credit balance for agents.', ['GET']),
      ep('mcp/v1/credit/history', 'MCP credit history', 'Credit history.', ['GET']),
      ep('mcp/v1/credit/spend', 'MCP spend', 'Spend credit.', ['POST']),
      ep('mcp/v1/credit/add', 'MCP add credit', 'Add credit (privileged).', ['POST']),
      ep('mcp/v1/payments', 'MCP payments', 'List payments.', ['GET']),
      ep('mcp/v1/payments/[id]', 'MCP payment', 'Payment detail.', ['GET']),
      ep('mcp/v1/store/products', 'MCP products', 'Store products.', ['GET']),
      ep('mcp/v1/store/products/[id]', 'MCP product', 'Product detail.', ['GET']),
      ep('mcp/v1/store/orders', 'MCP orders', 'Store orders.', ['GET']),
      ep('mcp/v1/store/orders/[id]', 'MCP order', 'Order detail.', ['GET']),
      ep('mcp/v1/store/orders/[id]/status', 'MCP order status', 'Update order status.', ['POST', 'PATCH']),
      ep('mcp/v1/store/vendors', 'MCP vendors', 'Vendors list.', ['GET']),
      ep('mcp/v1/store/vendors/[id]', 'MCP vendor', 'Vendor detail.', ['GET']),
      ep('mcp/v1/store/vendors/[id]/approve', 'MCP approve vendor', 'Approve a vendor.', ['POST']),
      ep('mcp/v1/store/vendors/[id]/suspend', 'MCP suspend vendor', 'Suspend a vendor.', ['POST']),
      ep('mcp/v1/images/generate', 'MCP images', 'Generate images via MCP.', ['POST']),
      ep('mcp/v1/videos/generate', 'MCP videos', 'Generate videos via MCP.', ['POST']),
    ],
  },
  {
    id: 'tunnel',
    label: 'Realtime tunnel',
    blurb: 'Subscribe, publish, SSE, and heartbeat — live event plane.',
    docsHref: '/docs/features/tunnel-protocol',
    docsLabel: 'Tunnel protocol',
    endpoints: [
      ep('tunnel/token', 'Tunnel token', 'Issue a short-lived tunnel auth token.', ['POST'], '/docs/features/tunnel-protocol'),
      ep('tunnel/subscribe', 'Subscribe', 'Subscribe to a channel / topic.', ['POST']),
      ep('tunnel/unsubscribe', 'Unsubscribe', 'Leave a channel.', ['POST']),
      ep('tunnel/publish', 'Publish', 'Publish an event to subscribers.', ['POST']),
      ep('tunnel/poll', 'Poll', 'Long-poll for events (fallback transport).', ['GET', 'POST']),
      ep('tunnel/sse', 'SSE stream', 'Server-Sent Events stream.', ['GET']),
      ep('tunnel/heartbeat', 'Heartbeat', 'Keep a tunnel session alive.', ['POST']),
      ep('tunnel/ping', 'Ping', 'Latency / liveness probe.', ['GET', 'POST']),
      ep('tunnel/disconnect', 'Disconnect', 'Tear down a tunnel session.', ['POST']),
      ep('tunnel/telemetry', 'Telemetry', 'Client tunnel telemetry ingest.', ['POST']),
      ep('tunnel/test', 'Tunnel test', 'Dev/test tunnel endpoint.', ['GET', 'POST']),
    ],
  },
  {
    id: 'cron',
    label: 'Scheduled jobs',
    blurb: 'Server cron routes — settlements, subscriptions, cleanup, training.',
    docsHref: '/docs/features/payment-conductor',
    docsLabel: 'PaymentConductor (cron context)',
    endpoints: [
      ep('cron/subscription-payment', 'Sub payment cron', 'Charge due subscriptions.', ['GET', 'POST']),
      ep('cron/subscription-expiry', 'Sub expiry cron', 'Expire lapsed memberships.', ['GET', 'POST']),
      ep('cron/settlement-payout', 'Settlement payout', 'Run affiliate / vendor settlements.', ['GET', 'POST']),
      ep('cron/solana-batch-payment', 'Solana batch pay', 'Batch on-chain payment jobs.', ['GET', 'POST']),
      ep('cron/credit-balance-monthly', 'Monthly credit', 'Monthly credit balance jobs.', ['GET', 'POST']),
      ep('cron/email-processor', 'Email processor', 'Process outbound / CRM email queue.', ['GET', 'POST']),
      ep('cron/email-analytics', 'Email analytics cron', 'Roll up email analytics.', ['GET', 'POST']),
      ep('cron/refcodes-mint', 'Refcode mint', 'Mint pending referral codes / NFTs.', ['GET', 'POST']),
      ep('cron/nft-gate-expiry', 'NFT gate expiry', 'Expire NFT-gated access.', ['GET', 'POST']),
      ep('cron/cleanup-reservations', 'Cleanup reservations', 'Clear stale reservations.', ['GET', 'POST']),
      ep('cron/cleanup-usernames', 'Cleanup usernames', 'Release reserved usernames.', ['GET', 'POST']),
      ep('cron/cleanup-news-deleted', 'Cleanup news', 'Purge soft-deleted news.', ['GET', 'POST']),
      ep('cron/train', 'Train matcher', 'Trigger matcher / model training jobs.', ['GET', 'POST']),
    ],
  },
  {
    id: 'web3',
    label: 'Web3, NFT & pools',
    blurb: 'Public pools, NFT market listings, and referral codes.',
    docsHref: '/docs/features/nft-market',
    docsLabel: 'NFT marketplace',
    endpoints: [
      ep('public-pools', 'Public pools', 'List contribution pools.', ['GET']),
      ep('public-pools/contribute', 'Contribute', 'Start a pool contribution.', ['POST']),
      ep('public-pools/contribute/confirm', 'Confirm contribute', 'Confirm an on-chain contribution.', ['POST']),
      ep('public-pools/signal', 'Pool signal', 'Signal interest / intent on a pool.', ['POST']),
      ep('nft-market/listings', 'NFT listings', 'Browse NFT market listings.', ['GET'], '/docs/features/nft-market'),
      ep('nft-market/listings/[id]', 'NFT listing', 'One listing detail.', ['GET']),
      ep('nft-market/listings/activate', 'Activate listing', 'Activate a listing for sale.', ['POST']),
      ep('refcodes', 'Referral codes', 'List referral codes.', ['GET'], '/docs/features/refcodes'),
      ep('refcodes/mint', 'Mint refcode', 'Mint a new referral code / NFT.', ['POST']),
      ep('refcodes/track', 'Track refcode', 'Record a referral click / attribution.', ['POST']),
    ],
  },
  {
    id: 'verification',
    label: 'Verification',
    blurb: 'Member document upload and verification procedure status.',
    docsHref: '/docs/api/admin',
    docsLabel: 'Admin verification',
    endpoints: [
      ep('verification/procedures/me', 'My procedures', 'List my verification procedures.', ['GET']),
      ep('verification/procedures/[procedureNumber]/documents', 'Upload documents', 'Attach documents to a procedure.', ['POST']),
      ep('verification/documents/[procedureNumber]/[documentId]', 'Document', 'Fetch or manage one document.', ['GET', 'DELETE']),
    ],
  },
  {
    id: 'analytics',
    label: 'Analytics & platform',
    blurb: 'Product analytics, health, uploads, and agent provisioning.',
    docsHref: '/docs/api',
    docsLabel: 'API Reference',
    endpoints: [
      ep('analytics/app', 'App analytics', 'Client app usage events.', ['POST']),
      ep('analytics/device', 'Device analytics', 'Device / client fingerprint events.', ['POST']),
      ep('analytics/navigation', 'Navigation analytics', 'Page / route navigation events.', ['POST']),
      ep('analytics/errors', 'Error analytics', 'Client error reports.', ['POST']),
      ep('analytics/web-vitals', 'Web vitals', 'Core Web Vitals beacons.', ['POST']),
      ep('analytics/platform-stats', 'Platform stats (auth)', 'Authenticated platform statistics.', ['GET']),
      ep('platform-stats', 'Platform stats (public)', 'Cached public platform statistics.', ['GET']),
      ep('health', 'Health', 'Liveness / readiness probe.', ['GET']),
      ep('info', 'Info', 'Build / environment info.', ['GET']),
      ep('uploads', 'Uploads', 'Generic authenticated file upload.', ['POST']),
      ep('test-db', 'Test DB', 'Database connectivity check (ops).', ['GET']),
      ep('v1/agents/provision', 'Provision agent', 'Provision a DAGI / AI agent instance.', ['POST']),
      ep('webhooks/email/inbound', 'Inbound email', 'Receive inbound email webhooks.', ['POST']),
    ],
  },
]

export const API_TREE_ROUTE_COUNT = API_TREE_FAMILIES.reduce(
  (n, f) => n + f.endpoints.length,
  0,
)

export function findEndpoint(id: string): {
  family: ApiFamilyNode
  endpoint: ApiEndpointNode
} | null {
  for (const family of API_TREE_FAMILIES) {
    const endpoint = family.endpoints.find((e) => e.id === id)
    if (endpoint) return { family, endpoint }
  }
  return null
}
