import { NextResponse } from 'next/server'

/** Dev-only probe: exercise the same CRM path as submitContactForm. */
export async function POST(request: Request) {
  if (process.env.NODE_ENV === 'production') {
    return NextResponse.json({ error: 'Not found' }, { status: 404 })
  }

  const step: string[] = ['start']
  try {
    const body = (await request.json().catch(() => ({}))) as {
      email?: string
      name?: string
      message?: string
    }
    step.push('parsed-body')
    const email = body.email || `probe-${Date.now()}@example.com`
    const name = body.name || 'CRM Probe'
    const message = body.message || 'probe message'

    step.push('importing-crm')
    const { getEmailContactService, getEmailTaskService } = await import(
      '@/features/email-crm/pipeline/crm'
    )
    step.push('imported-crm')

    const contactService = getEmailContactService()
    step.push('got-contact-service')
    const contact = await contactService.getOrCreateContact(email, {
      name,
      type: 'lead',
      tags: ['contact-form'],
      metadata: {
        message,
        entityId: 'contact_page',
        entityName: 'Contact Page',
        source: 'contact-form-probe',
      },
    })
    step.push(`contact:${contact.id}`)

    const taskService = getEmailTaskService()
    step.push('got-task-service')
    const task = await taskService.createTask({
      threadId: `contact-form:${contact.id}`,
      title: `Contact form: ${name}`,
      description: message,
      taskType: 'follow_up',
      dueDays: 1,
      priority: 'normal',
      autoGenerated: true,
      triggerReason: 'contact-form',
    })
    step.push(`task:${task.id}`)

    return NextResponse.json({
      ok: true,
      contactId: contact.id,
      email: contact.email,
      taskId: task.id,
      step,
    })
  } catch (error) {
    console.error('[contact-crm-probe]', step, error)
    return NextResponse.json(
      {
        ok: false,
        step,
        error: error instanceof Error ? error.message : String(error),
        stack: error instanceof Error ? error.stack?.split('\n').slice(0, 16) : undefined,
      },
      { status: 500 },
    )
  }
}
