/**
 * Institution program / investment → email-CRM bridge (minimal).
 *
 * Creates/updates a lead contact and an open review task so ops can follow up
 * in /admin/crm/contacts and /admin/crm/tasks.
 *
 * STUB / TODO — CRM Orders upgrade:
 * - Build admin CRM Orders page with new-order widget cards (project_orders + program/investment).
 * - Each order detail should open a built-in chat thread with the custom-order client
 *   (not email delivery) — reuse messenger/conversation primitives bound to orderId.
 * - PIPELINES.md: add `opportunity.program.crm_ingest` smoke when suite exists;
 *   later `crm.orders.chat_thread` for order↔client realtime chat.
 * - Replace synthetic threadId (`opp:{id}`) with a real opportunity-linked task model
 *   when email CRM moves off InMemory* repositories to Postgres SSOT.
 */

import { logger } from '@/lib/logger'
import { getEmailContactService, getEmailTaskService } from '@/features/email-crm/pipeline/crm'

export async function ingestProgramOpportunityToEmailCrm(input: {
  opportunityId: string
  title: string
  subtype: 'program' | 'investment' | string
  submitterEmail?: string | null
  submitterName?: string | null
  submitterUserId?: string | null
  entityName?: string | null
}): Promise<void> {
  const email = input.submitterEmail?.trim()
  if (!email) {
    logger.warn('[program-crm] skip ingest — no submitter email', {
      opportunityId: input.opportunityId,
    })
    return
  }

  try {
    const contacts = getEmailContactService()
    const contact = await contacts.getOrCreateContact(email, {
      name: input.submitterName ?? undefined,
      company: input.entityName ?? undefined,
      type: 'lead',
      tags: ['opportunity', 'program', input.subtype].filter(Boolean),
      metadata: {
        opportunityId: input.opportunityId,
        source: 'opportunity.program',
        subtype: input.subtype,
      },
      ringUserId: input.submitterUserId ?? undefined,
    })

    const tasks = getEmailTaskService()
    // Synthetic thread key until opportunity-linked tasks exist in PG
    const threadId = `opp:${input.opportunityId}`
    await tasks.createTask({
      threadId,
      title: `Review institution ${input.subtype}: ${input.title}`,
      description: `Opportunity ${input.opportunityId} submitted by ${email}. Contact ${contact.id}.`,
      taskType: 'review',
      priority: 'normal',
      autoGenerated: true,
      triggerReason: 'opportunity.program.create',
      dueDays: 3,
    })

    logger.info('[program-crm] ingest ok', {
      opportunityId: input.opportunityId,
      contactId: contact.id,
      threadId,
    })
  } catch (error) {
    // Non-blocking — opportunity create must succeed even if CRM is down
    logger.error('[program-crm] ingest failed', error)
  }
}
