'use server'

import { headers } from 'next/headers'
import { sendToTelegramBot } from '@/lib/telegram'
import { redirect } from 'next/navigation'
import { auth } from '@/auth'
import { rateLimit } from '@/lib/rate-limit'
import { getEmailContactService, getEmailTaskService } from '@/services/email/crm'

export interface ContactFormState {
  success?: boolean
  message?: string
  error?: string
}

export async function submitContactForm(
  prevState: ContactFormState | null,
  formData: FormData,
): Promise<ContactFormState> {
  const honeypot = formData.get('website') as string
  if (honeypot) {
    return { success: true, message: 'Thank you for your message!' }
  }

  const headersList = await headers()
  const ip =
    headersList.get('x-forwarded-for')?.split(',')[0]?.trim() ||
    headersList.get('x-real-ip') ||
    'unknown'
  const limit = rateLimit(`contact:${ip}`, 5, 60_000)
  if (!limit.ok) {
    return { error: 'Too many requests. Please try again in a minute.' }
  }

  const session = await auth()

  const entityId = formData.get('entityId') as string
  const entityName = formData.get('entityName') as string
  const name = formData.get('name') as string
  const email = formData.get('email') as string
  const message = formData.get('message') as string

  if (!name || !email || !message) {
    return { error: 'All fields are required' }
  }

  if (!/\S+@\S+\.\S+/.test(email)) {
    return { error: 'Please enter a valid email address' }
  }

  try {
    await sendToTelegramBot({
      entityId,
      entityName,
      name: session?.user?.name || name,
      email: session?.user?.email || email,
      message,
      userId: session?.user?.id,
    })
  } catch (error) {
    console.error('Error sending contact form to Telegram:', error)
    return { error: 'Failed to send message. Please try again.' }
  }

  try {
    const contactService = getEmailContactService()
    const contact = await contactService.getOrCreateContact(email, {
      name: session?.user?.name || name,
      type: 'lead',
      tags: ['contact-form'],
      metadata: {
        message,
        entityId,
        entityName,
        source: 'contact-form',
      },
      ringUserId: session?.user?.id,
    })

    const taskService = getEmailTaskService()
    await taskService.createTask({
      threadId: contact.id,
      title: `Contact form: ${name}`,
      description: message,
      taskType: 'follow_up',
      dueDays: 1,
      priority: 'normal',
      autoGenerated: true,
      triggerReason: 'contact-form',
    })
  } catch (crmError) {
    console.warn('CRM lead pipeline skipped (Telegram delivered):', crmError)
  }

  redirect('/contact/thank-you')
}
