import type { ModelEntry } from './types'

const OPENAI_PRICING = 'https://developers.openai.com/api/docs/pricing'
const ANTHROPIC_PRICING = 'https://platform.claude.com/docs/en/about-claude/pricing'
const XAI_DOCS = 'https://docs.x.ai'
const AS_OF = '2026-08-03'

/** Ring SSOT model catalog — seed with known data; expand preferred lists later. */
export const MODEL_CATALOG: ModelEntry[] = [
  // —— OpenAI ——
  {
    provider: 'openai',
    modelId: 'gpt-5.6-sol',
    displayName: 'GPT-5.6 Sol',
    modalities: ['text'],
    methods: [
      { name: 'chat', http: 'POST', path: '/chat/completions' },
      { name: 'responses', http: 'POST', path: '/responses' },
    ],
    capabilities: { tools: true, stream: true, vision: true, structuredOutput: true },
    pricing: { unit: 'per_mtok', inputUsd: 5, outputUsd: 30, cachedInputUsd: 0.5, asOf: AS_OF, source: OPENAI_PRICING },
    keyEnv: ['OPENAI_API_KEY'],
    defaultBaseUrl: 'https://api.openai.com/v1',
    status: 'active',
  },
  {
    provider: 'openai',
    modelId: 'gpt-5.6-terra',
    displayName: 'GPT-5.6 Terra',
    modalities: ['text'],
    methods: [
      { name: 'chat', http: 'POST', path: '/chat/completions' },
      { name: 'responses', http: 'POST', path: '/responses' },
    ],
    capabilities: { tools: true, stream: true, vision: true, structuredOutput: true },
    pricing: { unit: 'per_mtok', inputUsd: 2.5, outputUsd: 15, cachedInputUsd: 0.25, asOf: AS_OF, source: OPENAI_PRICING },
    keyEnv: ['OPENAI_API_KEY'],
    defaultBaseUrl: 'https://api.openai.com/v1',
    status: 'active',
  },
  {
    provider: 'openai',
    modelId: 'gpt-5.6-luna',
    displayName: 'GPT-5.6 Luna',
    modalities: ['text'],
    methods: [
      { name: 'chat', http: 'POST', path: '/chat/completions' },
      { name: 'responses', http: 'POST', path: '/responses' },
    ],
    capabilities: { tools: true, stream: true, vision: true, structuredOutput: true },
    pricing: { unit: 'per_mtok', inputUsd: 1, outputUsd: 6, cachedInputUsd: 0.1, asOf: AS_OF, source: OPENAI_PRICING },
    keyEnv: ['OPENAI_API_KEY'],
    defaultBaseUrl: 'https://api.openai.com/v1',
    status: 'active',
  },
  {
    provider: 'openai',
    modelId: 'gpt-4o',
    displayName: 'GPT-4o (deprecated default)',
    modalities: ['text'],
    methods: [{ name: 'chat', http: 'POST', path: '/chat/completions' }],
    capabilities: { tools: true, stream: true, vision: true },
    pricing: { unit: 'per_mtok', inputUsd: 2.5, outputUsd: 10, asOf: AS_OF, source: OPENAI_PRICING },
    keyEnv: ['OPENAI_API_KEY'],
    defaultBaseUrl: 'https://api.openai.com/v1',
    status: 'deprecated',
  },
  {
    provider: 'openai',
    modelId: 'text-embedding-3-small',
    displayName: 'text-embedding-3-small',
    modalities: ['embedding'],
    methods: [{ name: 'embeddings', http: 'POST', path: '/embeddings' }],
    capabilities: {},
    pricing: { unit: 'per_mtok', inputUsd: 0.02, asOf: AS_OF, source: OPENAI_PRICING },
    keyEnv: ['OPENAI_API_KEY'],
    defaultBaseUrl: 'https://api.openai.com/v1',
    status: 'active',
  },

  // —— Anthropic ——
  {
    provider: 'anthropic',
    modelId: 'claude-opus-4-20250514',
    displayName: 'Claude Opus 4',
    modalities: ['text'],
    methods: [
      { name: 'messages', http: 'POST', path: '/v1/messages' },
      { name: 'models.list', http: 'GET', path: '/v1/models' },
    ],
    capabilities: { tools: true, stream: true, vision: true, structuredOutput: true, imageInput: true },
    pricing: { unit: 'per_mtok', inputUsd: 15, outputUsd: 75, asOf: AS_OF, source: ANTHROPIC_PRICING },
    keyEnv: ['ANTHROPIC_API_KEY'],
    defaultBaseUrl: 'https://api.anthropic.com',
    status: 'active',
  },
  {
    provider: 'anthropic',
    modelId: 'claude-sonnet-4-5-20250929',
    displayName: 'Claude Sonnet 4.5',
    modalities: ['text'],
    methods: [
      { name: 'messages', http: 'POST', path: '/v1/messages' },
      { name: 'models.list', http: 'GET', path: '/v1/models' },
    ],
    capabilities: { tools: true, stream: true, vision: true, structuredOutput: true, imageInput: true },
    pricing: { unit: 'per_mtok', inputUsd: 3, outputUsd: 15, asOf: AS_OF, source: ANTHROPIC_PRICING },
    keyEnv: ['ANTHROPIC_API_KEY'],
    defaultBaseUrl: 'https://api.anthropic.com',
    status: 'active',
  },
  {
    provider: 'anthropic',
    modelId: 'claude-sonnet-4-20250514',
    displayName: 'Claude Sonnet 4',
    modalities: ['text'],
    methods: [{ name: 'messages', http: 'POST', path: '/v1/messages' }],
    capabilities: { tools: true, stream: true, vision: true, structuredOutput: true, imageInput: true },
    pricing: { unit: 'per_mtok', inputUsd: 3, outputUsd: 15, asOf: AS_OF, source: ANTHROPIC_PRICING },
    keyEnv: ['ANTHROPIC_API_KEY'],
    defaultBaseUrl: 'https://api.anthropic.com',
    status: 'active',
  },
  {
    provider: 'anthropic',
    modelId: 'claude-haiku-4-5-20250514',
    displayName: 'Claude Haiku 4.5',
    modalities: ['text'],
    methods: [{ name: 'messages', http: 'POST', path: '/v1/messages' }],
    capabilities: { tools: true, stream: true, vision: true, structuredOutput: true },
    pricing: { unit: 'per_mtok', inputUsd: 0.25, outputUsd: 1.25, asOf: AS_OF, source: ANTHROPIC_PRICING },
    keyEnv: ['ANTHROPIC_API_KEY'],
    defaultBaseUrl: 'https://api.anthropic.com',
    status: 'active',
  },
  {
    provider: 'anthropic',
    modelId: 'claude-3-5-sonnet-20241022',
    displayName: 'Claude 3.5 Sonnet (deprecated default)',
    modalities: ['text'],
    methods: [{ name: 'messages', http: 'POST', path: '/v1/messages' }],
    capabilities: { tools: true, stream: true, vision: true },
    pricing: { unit: 'per_mtok', inputUsd: 3, outputUsd: 15, asOf: AS_OF, source: ANTHROPIC_PRICING },
    keyEnv: ['ANTHROPIC_API_KEY'],
    defaultBaseUrl: 'https://api.anthropic.com',
    status: 'deprecated',
  },

  // —— xAI ——
  {
    provider: 'xai',
    modelId: 'grok-4.3',
    displayName: 'Grok 4.3',
    modalities: ['text'],
    methods: [
      { name: 'chat', http: 'POST', path: '/chat/completions' },
      { name: 'responses', http: 'POST', path: '/responses' },
    ],
    capabilities: {
      tools: true,
      stream: true,
      webSearch: true,
      structuredOutput: true,
    },
    pricing: { unit: 'per_mtok', inputUsd: 1.25, outputUsd: 2.5, cachedInputUsd: 0.2, asOf: AS_OF, source: XAI_DOCS },
    keyEnv: ['XAI_TEXT_API_KEY', 'XAI_API_KEY'],
    baseUrlEnv: 'XAI_API_BASE_URL',
    defaultBaseUrl: 'https://api.x.ai/v1',
    status: 'active',
  },
  {
    provider: 'xai',
    modelId: 'grok-imagine-image-quality',
    displayName: 'Grok Imagine Image Quality',
    modalities: ['image'],
    methods: [
      { name: 'images.generate', http: 'POST', path: '/images/generations' },
      { name: 'images.edit', http: 'POST', path: '/images/edits' },
    ],
    capabilities: { imageInput: true },
    pricing: { unit: 'per_image', flatUsd: 0.07, asOf: AS_OF, source: XAI_DOCS },
    keyEnv: ['XAI_IMAGE_API_KEY', 'XAI_API_KEY'],
    baseUrlEnv: 'XAI_API_BASE_URL',
    defaultBaseUrl: 'https://api.x.ai/v1',
    status: 'active',
  },
  {
    provider: 'xai',
    modelId: 'grok-imagine-video-1.5',
    displayName: 'Grok Imagine Video 1.5',
    modalities: ['video'],
    methods: [
      { name: 'videos.generate', http: 'POST', path: '/videos/generations' },
      { name: 'videos.edit', http: 'POST', path: '/videos/edits' },
      { name: 'videos.extend', http: 'POST', path: '/videos/extensions' },
    ],
    capabilities: { imageInput: true },
    pricing: { unit: 'per_video_second', flatUsd: 0.05, asOf: AS_OF, source: XAI_DOCS },
    keyEnv: ['XAI_VIDEO_API_KEY', 'XAI_API_KEY'],
    baseUrlEnv: 'XAI_API_BASE_URL',
    defaultBaseUrl: 'https://api.x.ai/v1',
    status: 'active',
  },
  {
    provider: 'xai',
    modelId: 'grok-imagine-video',
    displayName: 'Grok Imagine Video',
    modalities: ['video'],
    methods: [
      { name: 'videos.generate', http: 'POST', path: '/videos/generations' },
      { name: 'videos.edit', http: 'POST', path: '/videos/edits' },
    ],
    capabilities: { imageInput: true },
    pricing: { unit: 'per_video_second', flatUsd: 0.05, asOf: AS_OF, source: XAI_DOCS },
    keyEnv: ['XAI_VIDEO_API_KEY', 'XAI_API_KEY'],
    baseUrlEnv: 'XAI_API_BASE_URL',
    defaultBaseUrl: 'https://api.x.ai/v1',
    status: 'active',
  },
  {
    provider: 'xai',
    modelId: 'grok-tts-eve',
    displayName: 'xAI TTS (eve)',
    modalities: ['audio'],
    methods: [{ name: 'tts', http: 'POST', path: '/tts' }],
    capabilities: {},
    pricing: { unit: 'per_minute', flatUsd: 0.05, asOf: AS_OF, source: XAI_DOCS },
    keyEnv: ['XAI_API_KEY'],
    baseUrlEnv: 'XAI_API_BASE_URL',
    defaultBaseUrl: 'https://api.x.ai/v1',
    status: 'active',
  },

  // —— Google ——
  {
    provider: 'google',
    modelId: 'imagen-4.0-generate-001',
    displayName: 'Imagen 4',
    modalities: ['image'],
    methods: [{ name: 'images.generate', http: 'POST', path: '/models/{model}:predict' }],
    capabilities: {},
    pricing: { unit: 'per_image', flatUsd: 0.04, asOf: AS_OF, source: 'https://ai.google.dev/pricing' },
    keyEnv: ['GOOGLE_GENAI_API_KEY'],
    baseUrlEnv: 'GOOGLE_GENAI_BASE_URL',
    defaultBaseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    status: 'active',
  },
  {
    provider: 'google',
    modelId: 'gemini-3-flash',
    displayName: 'Gemini 3 Flash',
    modalities: ['text'],
    methods: [{ name: 'chat', http: 'POST', path: '/models/{model}:generateContent' }],
    capabilities: { tools: true, stream: true, vision: true },
    pricing: { unit: 'per_mtok', inputUsd: 0.5, outputUsd: 3, asOf: AS_OF, source: 'https://ai.google.dev/pricing' },
    keyEnv: ['GOOGLE_GENAI_API_KEY'],
    baseUrlEnv: 'GOOGLE_GENAI_BASE_URL',
    defaultBaseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    status: 'preview',
  },

  // —— OpenRouter (passthrough ids) ——
  {
    provider: 'openrouter',
    modelId: 'anthropic/claude-sonnet-4-5',
    displayName: 'OpenRouter Claude Sonnet 4.5',
    modalities: ['text'],
    methods: [{ name: 'chat', http: 'POST', path: '/chat/completions' }],
    capabilities: { tools: true, stream: true, vision: true, structuredOutput: true },
    pricing: { unit: 'per_mtok', inputUsd: 3, outputUsd: 15, asOf: AS_OF, source: 'openrouter upstream' },
    keyEnv: ['OPENROUTER_API_KEY'],
    defaultBaseUrl: 'https://openrouter.ai/api/v1',
    status: 'active',
  },
  {
    provider: 'openrouter',
    modelId: 'openai/gpt-4o-mini',
    displayName: 'OpenRouter GPT-4o mini',
    modalities: ['text'],
    methods: [{ name: 'chat', http: 'POST', path: '/chat/completions' }],
    capabilities: { tools: true, stream: true },
    pricing: { unit: 'per_mtok', inputUsd: 0.15, outputUsd: 0.6, asOf: AS_OF, source: 'openrouter upstream' },
    keyEnv: ['OPENROUTER_API_KEY'],
    defaultBaseUrl: 'https://openrouter.ai/api/v1',
    status: 'active',
  },

  // —— Suno ——
  {
    provider: 'suno',
    modelId: 'V4',
    displayName: 'Suno V4',
    modalities: ['audio'],
    methods: [{ name: 'music', http: 'POST', path: '/api/generate' }],
    capabilities: {},
    pricing: { unit: 'per_request', flatUsd: 0.1, asOf: AS_OF, source: 'suno' },
    keyEnv: ['SUNO_API_KEY'],
    defaultBaseUrl: 'https://api.sunoapi.org',
    status: 'active',
  },
]

export function findCatalogEntry(
  provider: string,
  modelId: string,
): ModelEntry | undefined {
  return MODEL_CATALOG.find((e) => e.provider === provider && e.modelId === modelId)
}
