/**
 * Email CRM task types — no runtime deps (breaks Jsonb require cycle).
 */

export type TaskType = 'follow_up' | 'escalation' | 'action_required' | 'review'
export type TaskStatus = 'open' | 'in_progress' | 'completed' | 'cancelled' | 'overdue'
export type TaskPriority = 'low' | 'normal' | 'high' | 'urgent'

export interface EmailTask {
  id: string
  threadId: string
  messageId: string | null
  title: string
  description: string | null
  taskType: TaskType
  dueDate: Date | null
  assignedTo: string | null
  status: TaskStatus
  priority: TaskPriority
  autoGenerated: boolean
  triggerReason: string | null
  completedAt: Date | null
  completedBy: string | null
  completionNotes: string | null
  createdAt: Date
  updatedAt: Date
}

export interface TaskCreateInput {
  threadId: string
  messageId?: string
  title: string
  description?: string
  taskType: TaskType
  dueDate?: Date
  dueDays?: number
  assignedTo?: string
  priority?: TaskPriority
  autoGenerated?: boolean
  triggerReason?: string
}

export interface TaskUpdateInput {
  title?: string
  description?: string
  dueDate?: Date
  assignedTo?: string
  status?: TaskStatus
  priority?: TaskPriority
}

export interface TaskCompleteInput {
  completedBy: string
  completionNotes?: string
}

export interface TaskSearchParams {
  threadId?: string
  assignedTo?: string
  status?: TaskStatus | TaskStatus[]
  taskType?: TaskType
  priority?: TaskPriority | TaskPriority[]
  dueBefore?: Date
  dueAfter?: Date
  limit?: number
  offset?: number
}

export interface TaskAutoCreationRule {
  id: string
  name: string
  conditions: {
    intent?: string[]
    sentiment?: string[]
    priority?: string[]
    isFirstContact?: boolean
    hasAttachments?: boolean
  }
  action: {
    taskType: TaskType
    titleTemplate: string
    descriptionTemplate?: string
    priority: TaskPriority
    dueDays: number
    assignedTo?: string
  }
  enabled: boolean
}

export interface TaskRepository {
  findById(id: string): Promise<EmailTask | null>
  findByThreadId(threadId: string): Promise<EmailTask[]>
  create(input: TaskCreateInput): Promise<EmailTask>
  update(id: string, input: TaskUpdateInput): Promise<EmailTask>
  complete(id: string, input: TaskCompleteInput): Promise<EmailTask>
  search(params: TaskSearchParams): Promise<EmailTask[]>
  markOverdue(): Promise<number>
  delete(id: string): Promise<void>
}
