/**
 * Curated professional position / role tags for profile Position tag-cloud.
 * Free-form user tags are merged at runtime; suggestions filter at 3+ chars.
 */
export const KNOWN_POSITION_TAGS: readonly string[] = [
  'Founder',
  'Co-Founder',
  'CEO',
  'CTO',
  'COO',
  'CFO',
  'CMO',
  'Product Manager',
  'Engineering Manager',
  'Software Engineer',
  'Frontend Engineer',
  'Backend Engineer',
  'Full-Stack Engineer',
  'DevOps Engineer',
  'Data Engineer',
  'Data Scientist',
  'Designer',
  'UX Designer',
  'UI Designer',
  'Product Designer',
  'Marketing Manager',
  'Growth Lead',
  'Sales Manager',
  'Account Executive',
  'Customer Success',
  'Community Manager',
  'Content Creator',
  'Researcher',
  'Consultant',
  'Advisor',
  'Investor',
  'Lawyer',
  'Accountant',
  'Teacher',
  'Student',
  'Freelancer',
  'Contractor',
  'Intern',
  'Volunteer',
  'Director',
  'VP Engineering',
  'VP Product',
  'VP Sales',
  'Head of Marketing',
  'Head of Operations',
  'Project Manager',
  'Scrum Master',
  'QA Engineer',
  'Security Engineer',
  'Mobile Developer',
  'AI Engineer',
  'Blockchain Developer',
  'Journalist',
  'Editor',
  'Doctor',
  'Nurse',
  'Architect',
  'Farmer',
  'Mechanic',
  'Driver',
  'Artist',
  'Musician',
  'Photographer',
]

export {
  PROFILE_TAG_MIN_CHARS as POSITION_TAG_MIN_CHARS,
  parseProfileTags as parsePositionTags,
  serializeProfileTags as serializePositionTags,
  filterProfileTags as filterPositionTags,
} from '@/features/auth/lib/profile-tags'
