/**
 * Curated skills / expertise tags for profile Skills tag-cloud.
 */
export const KNOWN_SKILL_TAGS: readonly string[] = [
  'React',
  'Next.js',
  'TypeScript',
  'JavaScript',
  'Node.js',
  'Python',
  'Go',
  'Rust',
  'Java',
  'Kotlin',
  'Swift',
  'PostgreSQL',
  'Redis',
  'GraphQL',
  'REST APIs',
  'Docker',
  'Kubernetes',
  'AWS',
  'GCP',
  'Azure',
  'DevOps',
  'CI/CD',
  'Tailwind CSS',
  'UI/UX',
  'Figma',
  'Product Management',
  'Project Management',
  'Agile',
  'Scrum',
  'AI / ML',
  'Prompt Engineering',
  'Blockchain',
  'Solidity',
  'Web3',
  'SEO',
  'Content Writing',
  'Copywriting',
  'Marketing',
  'Sales',
  'Customer Success',
  'Community Building',
  'Public Speaking',
  'Technical Writing',
  'Data Analysis',
  'SQL',
  'Mobile Development',
  'iOS',
  'Android',
  'QA / Testing',
  'Security',
  'System Design',
  'Architecture',
  'Leadership',
  'Mentoring',
  'Ring Platform',
  'Auth.js',
  'PostgreSQL + PostGIS',
]
